---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <USERNAME>
spec:
  project: workshops
  source:
    path: <PATH_WITHIN_REPO>
    repoURL: <YOUR_REPO_URL>
    targetRevision: HEAD
  destination:
    namespace: workshop-<USERNAME>
    name: ml-prague-workshop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
