name: Conftest

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: instrumenta/conftest-action@master
        with:
          files: ${{ steps.files.outputs.all }}
