name: Conftest

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: instrumenta/conftest-action@master
        with:
          files: "**/*.yaml"
